{% set name = "mne" %}
{% set version = "0.18.2" %}
{% set sha256 = "aa2e72ad3225efdad39b05e67cd5c88dbd5c3fabf5e1705e459347131f114bc6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - dipy
    - matplotlib
    - nibabel
    - numpy
    - scikit-learn
    - scipy
    - mayavi
    - pysurfer

test:
  imports:
    - mne
  commands:
    - mne

about:
  home: http://martinos.org/mne
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'MNE python project for MEG and EEG data analysis.'
  description: |
    MNE python project for MEG and EEG data analysis.
  doc_url: http://martinos.org/mne
  dev_url: https://github.com/mne-tools/mne-python

extra:
  recipe-maintainers:
    - larsoner
    - christianbrodbeck
